### ISSUE TITLE
Notation question

### ISSUE THREAD

**Issue by ib00** [eugenedeon/hitchhikersscatter#1]
What is '\sigma' in your BRDF definitions?

For example:
https://github.com/eugenedeon/hitchhikersscatter/blob/master/code/boundaries/NDFs/Beckmann_NDF.pdf
(definition in In[1149])

**Comment by eugenedeon** [comment]
\sigma is the cross section / extinction coefficient for a half space of participating media that simulates the rough surface.  In the Smith model, such a medium can exactly describe the reflectance in this way, and \sigma(\omega) depends on the direction that the ray is travelling and is independent of the depth in the half space.  It is related to Smith's \Lambda function by a cosine factor.

**Comment by ib00** [comment]
I haven't seen this definition before (for BRDFs) -- is there a good reference for it?

The point is to unify surface and volume scattering?

**Comment by eugenedeon** [comment]
Yes, surface scattering under Smith's assumptions can be formulated exactly as a homogeneous half space volume.  See:
https://eheitzresearch.wordpress.com/240-2/
and:
http://onrendering.com/data/papers/ms16/ms16.pdf
